service: backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  # 1. Environment variables available to your code via process.env
  environment:
    DYNAMODB_TABLE_NAME: ${self:service}-listings-${sls:stage}
    S3_BUCKET_NAME: sg-happenings-s3
    CLOUDFRONT_URL: https://d2yx0dms1vpwng.cloudfront.net
  # 2. Grant permissions to your Lambda function to talk to DynamoDB and S3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ ListingsTable, Arn ]
            - Fn::Join: [ '/', [ { Fn::GetAtt: [ ListingsTable, Arn ] }, 'index', '*' ] ]
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - "arn:aws:s3:::sg-happenings-s3/*"

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - '@aws-sdk/*'

functions:
  api:
    handler: app.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: ANY
          cors: true
      - httpApi:
          path: '/'
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useHttpApi: true
    noAuth: true

# 3. Infrastructure as Code: Automatically spins up your exact table structure in AWS!
resources:
  Resources:
    ListingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-listings-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: district
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: DistrictIndex
            KeySchema:
              - AttributeName: district
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: TypeIndex
            KeySchema:
              - AttributeName: type
                KeyType: HASH
            Projection:
              ProjectionType: ALL